Switch to theme components w/ docsy-plus and use config dir
acend/container-basics-training pull request #61
Opened 2020-12-27 20:22 UTC by johanngyger

* https://gohugo.io/hugo-modules/theme-components
* https://github.com/puzzle/docsy-plus
* https://gohugo.io/getting-started/configuration/#configuration-directory

2020-12-27 21:49 UTC, aymonc submitted a review, later dismissed

2020-12-28 11:14 UTC, bliemli requested changes

2020-12-28 11:14 UTC, bliemli commented on README.md
> +Alternatively you can use the Puzzle setup from [config/acend](config/puzzle/config.toml), which is enabled with
```suggestion
Alternatively you can use the Puzzle setup from [config/puzzle](config/puzzle/config.toml), which is enabled with
```

2020-12-28 11:14 UTC, bliemli commented on README.md
> +### Docsy Theme Usage
```suggestion
### Docsy theme usage
```

2020-12-28 12:34 UTC, bliemli approved these changes

2020-12-28 12:39 UTC, merged